### ISSUE TITLE
Assert-Throw doesn't seem to match message

### ISSUE THREAD

**Issue by alx9r** [nohwnd/Assert#24]
The test

```PowerShell
Describe 'match message' {
    It 'Assert-Throw' {
        {throw 'a' } | Assert-Throw -Message '25fd4977'
    }
}
```
passes.  I didn't expect it to pass because the value passed to `-Message` does not appear in the exeption.

**Comment by nohwnd** [comment]
That’s odd, will have a look.

**Comment by nohwnd** [comment]
It's not a bug, rather it's a [naming issue](https://github.com/nohwnd/Assert/issues/13#issuecomment-319937832). The parameter you provided is the `Message` to show when the assertion failes, which means that any `Exception` will pass the test. You did produce an exception and hence the test passed and your message was not used. In the linked issue I expected this problem (but totally forgot about how it works and you scared me a with what seemed like a severe bug 😄  ). 

```powershell
get-module pester, assert | remove-module 
import-module pester -RequiredVersion 4.1.0
import-module .\Assert.psm1

Describe 'match message' {
    It 'Assert-Throw' {
        {throw 'a' } | Assert-Throw -ExceptionMessage '25fd4977'
    }
}
```
```
  [-] Assert-Throw 0.99s
    AssertionException: Expected an exception, with message '25fd4977' to be thrown, but the message was 'a'.
    at Assert-Throw, C:\projects\assert\src\Exception\Assert-Throw.ps1: line 75
    at <ScriptBlock>, <No file>: line 7
```

**Comment by nohwnd** [comment]
Renamed to `CustomMessage` in b8beb7f3772316d832ae1f8254f5855c282ec9a1
