### ISSUE TITLE
[Question] Use of this module outside Pester

### ISSUE THREAD

**Issue by LaurentDardenne** [nohwnd/Assert#46]
Hi,
I would like to know if this module of assertions can be used outside of Pester, i.e. in a module of treatment. For use similar to [this](https://en.wikipedia.org/wiki/Assertion_(software_development)#Assertions_in_production_environment).

**Comment by nohwnd** [comment]
Yes, it can, it has no ties to Pester. Outside of an It block it will simply throw an exception.

**Comment by LaurentDardenne** [comment]
Thank you.
